import { createRequire } from 'node:module';
import { resolve } from 'node:path';
import { readFileSync } from 'node:fs';
import assert from 'node:assert/strict';
const require=createRequire(resolve(process.argv[2], 'package.json'));
const {PGlite}=require('@electric-sql/pglite'); const db=new PGlite();
const ids=[1,2,3].map(n=>`00000000-0000-0000-0000-${String(n).padStart(12,'0')}`);
await db.exec(`create role anon; create role authenticated; create schema auth;
create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
grant usage on schema auth to authenticated;
create table projects(id text primary key,status text);
create table members(id uuid primary key,project_id text,user_id uuid,name text,avatar text);
create table files(id bigint primary key,project_id text);
create table file_comments(id bigint generated always as identity primary key,file_id bigint references files(id) on delete cascade,author text,avatar text,text text);
grant select,insert,update,delete on file_comments to authenticated;
grant usage on sequence file_comments_id_seq to authenticated;
insert into projects values('p','active'),('q','active'); insert into files values(1,'p'),(2,'q');`);
for(let i=0;i<3;i++) await db.query('insert into members values($1,$2,$1,$3,$4)',[ids[i],i===2?'q':'p',`팀원${i}`,'팀']);
const sql=readFileSync(new URL('../supabase/migration_workspace_comment_reactions.sql',import.meta.url),'utf8');
await db.exec(sql); await db.exec(sql);
async function login(i){await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[ids[i]]);await db.exec('set role authenticated');}
await login(0);
const c=(await db.query("insert into file_comments(file_id,author,avatar,text,member_id) values(1,'위조','?', '좋아요 👍',$1) returning *",[ids[1]])).rows[0];
assert.equal(c.member_id,ids[0]); assert.equal(c.author,'팀원0');
await assert.rejects(db.query('update file_comments set member_id=$1 where id=$2',[ids[1],c.id]),/permission denied/);
await login(1);
await db.query('insert into file_comment_reactions(comment_id,member_id,emoji) values($1,$2,$3)',[c.id,ids[1],'👍']);
await assert.rejects(db.query('insert into file_comment_reactions(comment_id,member_id,emoji) values($1,$2,$3)',[c.id,ids[0],'❤️']),/row-level security/);
await assert.rejects(db.query('insert into file_comment_reactions(comment_id,member_id,emoji) values($1,$2,$3)',[c.id,ids[1],'invalid']),/check constraint/);
await login(0);
await db.query('delete from file_comment_reactions where comment_id=$1',[c.id]);
assert.equal((await db.query('select * from file_comment_reactions')).rows.length,1);
await login(2);
assert.equal((await db.query('select * from file_comment_reactions')).rows.length,0);
await assert.rejects(db.query('insert into file_comment_reactions(comment_id,member_id,emoji) values($1,$2,$3)',[c.id,ids[2],'👍']),/row-level security/);
await assert.rejects(db.query("insert into file_comments(file_id,text) values(1,'외부')"),/참여자/);
await login(1);
await db.query('delete from file_comment_reactions where comment_id=$1',[c.id]);
assert.equal((await db.query('select * from file_comment_reactions')).rows.length,0);
await db.exec("reset role; update projects set status='done' where id='p'");
await login(0);
await assert.rejects(db.query('insert into file_comment_reactions(comment_id,member_id,emoji) values($1,$2,$3)',[c.id,ids[0],'👍']),/row-level security/);
await assert.rejects(db.query("insert into file_comments(file_id,text) values(1,'종료')"),/진행 중인/);
await db.close(); console.log('PASS: comment author identity, emoji persistence/removal, spoofing protection, outsider isolation, closed project protection');
