import { createContext, useContext, useEffect, useState, type ReactNode } from "react";
import { ngrokHeaders } from "../api/rest/ngrok";

export type AuthUser = { id: string; email?: string; user_metadata?: Record<string, unknown> };
export type AuthSession = { user: AuthUser; accessToken: string; refreshToken: string; access_token: string };
interface AuthContextValue { user: AuthUser | null; session: AuthSession | null; loading: boolean; signIn: (email: string, password: string) => Promise<{ error: string | null }>; signUp: (email: string, password: string, displayName: string, signupType?: "admin") => Promise<{ error: string | null; signedIn: boolean }>; signOut: () => Promise<void>; updatePassword: (currentPassword: string, newPassword: string) => Promise<{ error: string | null }>; }
const AuthContext = createContext<AuthContextValue | null>(null);
const serverUrl = String(import.meta.env.VITE_API_URL ?? "").replace(/\/$/, "");
const storageKey = "talju-server-session";
async function serverRequest<T>(path: string, init: RequestInit = {}, token?: string) { if (!serverUrl) throw new Error("자체 서버 주소가 설정되지 않았습니다."); const headers = new Headers(init.headers); for (const [name, value] of Object.entries(ngrokHeaders(serverUrl))) headers.set(name, value); if (token) headers.set("Authorization", `Bearer ${token}`); if (init.body && !headers.has("Content-Type")) headers.set("Content-Type", "application/json"); const response = await fetch(`${serverUrl}${path}`, { ...init, headers }); const body = await response.json().catch(() => null); if (!response.ok) throw new Error(body?.message || "요청을 처리하지 못했습니다."); return body as T; }
function storedSession(): AuthSession | null { try { return JSON.parse(localStorage.getItem(storageKey) ?? "null"); } catch { return null; } }

export function AuthProvider({ children }: { children: ReactNode }) {
  const [session, setSession] = useState<AuthSession | null>(null); const [loading, setLoading] = useState(true);
  useEffect(() => {
    const saved = storedSession(); if (!saved) { setLoading(false); return; } void (async () => { try { let active = saved; try { active = { ...active, user: await serverRequest<AuthUser>("/auth/me", {}, active.accessToken) }; } catch { const fresh = await serverRequest<{ accessToken: string; refreshToken: string }>("/auth/refresh", { method: "POST", body: JSON.stringify({ refreshToken: active.refreshToken }) }); active = { ...active, ...fresh, user: await serverRequest<AuthUser>("/auth/me", {}, fresh.accessToken), access_token: fresh.accessToken }; } localStorage.setItem(storageKey, JSON.stringify(active)); setSession(active); } catch { localStorage.removeItem(storageKey); } finally { setLoading(false); } })();
  }, []);
  async function signIn(email: string, password: string) { try { const result = await serverRequest<Omit<AuthSession, "access_token">>("/auth/login", { method: "POST", body: JSON.stringify({ email, password }) }); const active = { ...result, access_token: result.accessToken }; localStorage.setItem(storageKey, JSON.stringify(active)); setSession(active); return { error: null }; } catch (error) { return { error: error instanceof Error ? error.message : "로그인하지 못했습니다." }; } }
  async function signUp(email: string, password: string, displayName: string, signupType?: "admin") { try { await serverRequest("/auth/signup", { method: "POST", body: JSON.stringify({ email, password, displayName, ...(signupType === "admin" ? { signupType } : {}) }) }); return { error: null, signedIn: false }; } catch (error) { return { error: error instanceof Error ? error.message : "가입하지 못했습니다.", signedIn: false }; } }
  async function signOut() { const current = session; localStorage.removeItem(storageKey); setSession(null); if (current) await serverRequest("/auth/logout", { method: "POST", body: JSON.stringify({ refreshToken: current.refreshToken }) }).catch(() => {}); }
  async function updatePassword(currentPassword: string, newPassword: string) { try { if (!session) throw new Error("로그인이 필요합니다."); const result = await serverRequest<{ accessToken: string; refreshToken: string }>("/auth/password", { method: "PATCH", body: JSON.stringify({ currentPassword, newPassword }) }, session.accessToken); const active = { ...session, ...result, access_token: result.accessToken }; localStorage.setItem(storageKey, JSON.stringify(active)); setSession(active); return { error: null }; } catch (error) { return { error: error instanceof Error ? error.message : "비밀번호를 변경하지 못했습니다." }; } }
  return <AuthContext.Provider value={{ user: session?.user ?? null, session, loading, signIn, signUp, signOut, updatePassword }}>{children}</AuthContext.Provider>;
}
export function useAuth() { const ctx = useContext(AuthContext); if (!ctx) throw new Error("useAuth must be used within an AuthProvider"); return ctx; }
